# Generated by Django 5.1.1 on 2025-03-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coruse',
            old_name='id',
            new_name='coruseid',
        ),
        migrations.AlterField(
            model_name='coruse',
            name='info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coruse',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
